In [1]:
import numpy as np

In [2]:
A1 = np.array([1, 2, 3])
A1

array([1, 2, 3])

In [3]:
type(A1)

numpy.ndarray

In [4]:
A2 = np.array([[1, 2, 3], [4, 5, 6]])
A2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(A2)

numpy.ndarray

In [6]:
A2+A2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
A[0]

array([1, 2, 3])

In [9]:
A[0, 0]

1

In [10]:
A[0][0]

1

In [11]:
A[:, 1]

array([2, 5])

In [12]:
A[1, :]

array([4, 5, 6])

In [13]:
A[:, ::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [14]:
A[0] = 10
A

array([[10, 10, 10],
       [ 4,  5,  6]])

In [15]:
A[0][0] = 100
A

array([[100,  10,  10],
       [  4,   5,   6]])

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A[:, ::-1]

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
B

array([[3, 2, 1],
       [6, 5, 4]])

In [19]:
B[0][0] = 0

In [20]:
A

array([[1, 2, 0],
       [4, 5, 6]])

In [21]:
B

array([[0, 2, 1],
       [6, 5, 4]])

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A.copy()
B = B[:, ::-1]

B[0][0] = 0

In [23]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
B

array([[0, 2, 1],
       [6, 5, 4]])

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[False, False, True], [True, False, True]])
A[B] = 0
A

array([[1, 2, 0],
       [0, 5, 0]])

In [26]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
A>3

array([[False, False, False],
       [ True,  True,  True]])

In [28]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A[A>3] = 0
A

array([[1, 2, 3],
       [0, 0, 0]])

In [29]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A[np.logical_or(A<2, A>4)] = 0
A

array([[0, 2, 3],
       [4, 0, 0]])

In [30]:
A1 = np.array([1, 2, 3])

In [31]:
A2 = np.array([[1, 2, 3], [4, 5, 6]])

In [32]:
A1.size

3

In [33]:
A2.size

6

In [34]:
A1.shape

(3,)

In [35]:
A2.shape

(2, 3)

In [36]:
A1.ndim

1

In [37]:
A2.ndim

2

In [38]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.size, A.ndim, A.shape, sep='\n')

6
2
(2, 3)


In [39]:
A = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [40]:
A.shape

(3, 4)

In [41]:
np.reshape(A, (4, 3))

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 3],
       [3, 3, 3]])

In [42]:
np.reshape(A, (2, 6))

array([[1, 1, 1, 1, 2, 2],
       [2, 2, 3, 3, 3, 3]])

In [43]:
A.reshape(2, 6)

array([[1, 1, 1, 1, 2, 2],
       [2, 2, 3, 3, 3, 3]])

In [44]:
A.reshape(4, 3, 3)

ValueError: cannot reshape array of size 12 into shape (4,3,3)

In [45]:
A

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [46]:
A.T

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
A.shape

(2, 3)

In [49]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

In [50]:
A.ravel().shape

(6,)

In [51]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [52]:
A.ravel().shape

(6,)

In [53]:
A = np.array([[1, 2], [3, 4]])
A.flatten()[1] = 100
A

array([[1, 2],
       [3, 4]])

In [54]:
A = np.array([[1, 2], [3, 4]])
A.ravel()[1] = 100
A

array([[  1, 100],
       [  3,   4]])

In [55]:
A = np.array([[1], [2], [3], [4], [5], [6]])
A

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [56]:
A.shape

(6, 1)

In [57]:
A.squeeze()

array([1, 2, 3, 4, 5, 6])

In [57]:
A.squeeze().shape

(6,)

In [58]:
A = np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

In [59]:
B = np.ones((3,2))
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
A1 = np.zeros_like(B)
A1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
B1 = np.ones_like(A)
B1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
A = np.ones((3, 2))
B = A.astype('str')

In [63]:
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
B

array([['1.0', '1.0'],
       ['1.0', '1.0'],
       ['1.0', '1.0']], dtype='<U32')

In [65]:
A = np.arange(9).reshape(3, 3)
A[A%2 != 0] = 0
A.flatten()

array([0, 0, 2, 0, 4, 0, 6, 0, 8])