In [35]:
import numpy as np

In [36]:
a = np.array([    [1, 2, 3],     [4, 5, 6],     [7, 8, 9]])
b = np.array([    [2, 3, 4],     [5, 6, 7],     [8, 9, 10]])

In [37]:
c = np.dot(a,b)

In [40]:
a = np.zeros(6)
b = np.arange(0, 10, 2)
c = a + b

print(c[4])

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [41]:
a = np.array([[0, 1, 2], [3, 4, 5]])

b = a.ravel()
print(b[0, 0])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [49]:
a = np.arange(1, 26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
b = np.ones_like(a)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
a = a / 3

In [70]:
c = np.dot(a, eye_5)
c.sum()

108.33333333333334

In [61]:
init_m = np.arange(1, 26).reshape(5, 5)
init_m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
divided_m = init_m / 3
divided_m

array([[0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [2.        , 2.33333333, 2.66666667, 3.        , 3.33333333],
       [3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ],
       [5.33333333, 5.66666667, 6.        , 6.33333333, 6.66666667],
       [7.        , 7.33333333, 7.66666667, 8.        , 8.33333333]])

In [65]:
eye_5 = np.ones(5)
eye_5

array([1., 1., 1., 1., 1.])

In [ ]:
mul_m = divided_m @ eye_5

In [ ]:
mul_m.sum()

In [60]:
c = np.dot(a,b)
c.sum()

541.6666666666667

In [39]:
np.sum(c)

864

In [2]:
A = np.arange(1, 5)
A = np.reshape(A, (2,2))
A

array([[1, 2],
       [3, 4]])

In [3]:
I = np.eye(2)*2
I

array([[2., 0.],
       [0., 2.]])

In [4]:
A*I

array([[2., 0.],
       [0., 8.]])

In [5]:
np.dot(A, I)

array([[2., 4.],
       [6., 8.]])

In [6]:
A = np.arange(1, 5)
A = np.reshape(A, (1,4))
A

array([[1, 2, 3, 4]])

In [7]:
A.T

array([[1],
       [2],
       [3],
       [4]])

In [8]:
A*A.T

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [9]:
np.dot(A, A.T)

array([[30]])

In [10]:
A = 2
B = 3

np.dot(A, B)

6

In [11]:
A = np.array([2, 3, 4])
B = 3

np.dot(A, B)

array([ 6,  9, 12])

In [12]:
A = np.array([2, 3, 4])
B = np.array([-2, 1, -1])

np.dot(A, B)

-5

In [13]:
A = np.array([[2, 3, 4], [5, 6, 7]])
B = 2

np.dot(A, B)

array([[ 4,  6,  8],
       [10, 12, 14]])

In [14]:
A = np.array([[2, 3, 4], [5, 6, 7]])
B = np.array([-2, 1, -1])

np.dot(A, B)

array([ -5, -11])

In [21]:
X = np.array([1, 3, 4, 5, 7])
X = np.reshape(X, (5,1))
X

array([[1],
       [3],
       [4],
       [5],
       [7]])

In [22]:
Y = np.array([6, 16, 21, 26, 36])
Y = np.reshape(Y, (5,1))
Y

array([[ 6],
       [16],
       [21],
       [26],
       [36]])

In [23]:
E = np.ones((5, 1))
E

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [24]:
X = np.hstack([E, X])
X

array([[1., 1.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 7.]])

In [25]:
X.T

array([[1., 1., 1., 1., 1.],
       [1., 3., 4., 5., 7.]])

In [26]:
A = np.dot(X.T, X)
A

array([[  5.,  20.],
       [ 20., 100.]])

In [27]:
np.linalg.det(A)

99.99999999999996

In [28]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 1.  , -0.2 ],
       [-0.2 ,  0.05]])

In [29]:
B = np.dot(X.T, Y)
B

array([[105.],
       [520.]])

In [30]:
w = np.dot(A_inv, B)
w

array([[1.],
       [5.]])

In [31]:
X

array([[1., 1.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 7.]])

In [32]:
w

array([[1.],
       [5.]])

In [33]:
np.dot(X, w)

array([[ 6.],
       [16.],
       [21.],
       [26.],
       [36.]])

In [34]:
Y

array([[ 6],
       [16],
       [21],
       [26],
       [36]])

In [29]:
np.dot(X, w) == Y

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])