
# Numpy array. Практическая работа

## Цель практической работы

Выполните задачи, чтобы потренироваться в использовании функционала NumPy.

## Что входит в практическое задание

10 задач на использование библиотеки NumPy.


## Что нужно сделать

Скачайте файл с заданием в материалах, откройте его через Jupyter Notebook и выполните задачи. Сверьтесь с ответами, представленными ниже. Обратите внимание, что это задание не нужно сдавать на проверку.


## Задачи


1. Создайте вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [3]:
import numpy as np

In [9]:
a = np.zeros(10, int)
a [4] = 1
a
# ваш код здесь

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2. Создайте вектор со значениями от 10 до 49.

In [10]:
# ваш код здесь
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Создайте матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [12]:
c = np.arange(0, 9).reshape(3,3)
c
# ваш код здесь

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Создайте массив 3x3x3 со случайными значениями.

In [37]:
a =np.array( np.random.randint(0, 9, 9)).reshape(3,3)
a


array([[3, 1, 3],
       [7, 7, 7],
       [5, 3, 6]])

In [49]:
4*4*4*4

256

In [50]:
A = np.random.randint(1,100, 256)
A = A.reshape((4,4,4,4)) # не бойтесь брать размерность больше - сам функционал не меняется
A

array([[[[81, 90, 12, 76],
         [67, 76, 46, 60],
         [84, 41, 63, 89],
         [38, 58, 35, 61]],

        [[20, 38, 90, 28],
         [74, 57, 60, 53],
         [10, 81, 69,  1],
         [36, 96, 11, 39]],

        [[97,  1, 83, 83],
         [53, 88, 89,  3],
         [34, 64, 55, 51],
         [23, 23, 80, 44]],

        [[16, 93, 33, 95],
         [38, 36,  1, 94],
         [90, 32, 41, 19],
         [ 6, 78, 93, 42]]],


       [[[13, 43, 38, 39],
         [65, 33, 14, 71],
         [ 2, 25, 88, 46],
         [72, 19, 26, 60]],

        [[54, 41, 37, 51],
         [ 2,  5, 42, 38],
         [13, 80, 32, 15],
         [66, 11, 18, 96]],

        [[59, 22, 87, 23],
         [65, 28, 37, 52],
         [38, 18,  7, 81],
         [45, 52, 89, 97]],

        [[57, 73, 93, 17],
         [65, 50, 25, 19],
         [96, 85, 46, 31],
         [ 8, 14, 82, 78]]],


       [[[79, 17, 71, 89],
         [72, 59, 29, 37],
         [32, 19, 63, 70],
         [57, 50, 16, 94]],

      

5. Создайте матрицу 10x10 с 0 внутри и 1 на границах.

In [64]:
# ваш код здесь
q = np.zeros(8**2).reshape(8,8)
q = np.vstack([q, np.ones(8).reshape(1,8)])
q = np.vstack([np.ones(8).reshape(1,8), q])
q = np.hstack([q, np.ones(10).reshape(10,1)])
q = np.hstack([np.ones(10).reshape(10,1), q])

In [65]:
q

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6. Создайте матрицы  5x3 и 3x2 со случайными значениями и перемножьте их.

In [80]:
# ваш код здесь
a = np.array(np.random.randint(0,100,15)).reshape(5,3)

b = np.array(np.random.randint(0,100,6)).reshape(3,2)

                                                 
c = np.dot(a,b)
c

array([[7230, 4413],
       [2409, 3626],
       [3361, 5845],
       [7262, 2598],
       [6075, 6096]])

Для выполнения задач 7–10 создайте массив 10x10 со значениями от 1 до 100 и все вычисления производите на нём.



In [81]:
a = np.array(np.random.randint(1, 101, 100)).reshape(10, 10)
a

array([[ 30,   8,  59,  48,  44,  85,   4,  87,  72, 100],
       [ 84,  45,  85,  22,  57,  56,  32,  75,  84,  91],
       [ 45,  31,  71,  19,  45,  38,  46,   3,  21,  33],
       [ 83,  51,  98,   4,  86,  40,  54,  28,  10,  83],
       [ 63,  71,   3,  71,  43,  30,  58,  82,   5,  40],
       [ 84,  45,  62,  21,  39,  67,  69,  55,  94,  47],
       [  7,  57,  60,  30,  93,  90,  67,  17,  27,  80],
       [ 86,  92,  58,  83,  60,  64,  93,  14,  62,  85],
       [ 31,  42,  58,  64,  27, 100,  70,  96,  99,  93],
       [ 72,   2,  44,  32,  79,  51,   8,  54,  40, 100]])

7. Замените максимальный элемент матрицы на ноль.

In [89]:
# ваш код здесьa
a[a == a.max()] = 0
a[a == a.max()] 


array([94])

8. Отнимите среднее из каждой строки в матрице.

In [92]:
# ваш код здесь
a = a - a.mean()

In [93]:
a

array([[-19., -41.,  10.,  -1.,  -5.,  36., -45.,  38.,  23., -49.],
       [ 35.,  -4.,  36., -27.,   8.,   7., -17.,  26.,  35.,  42.],
       [ -4., -18.,  22., -30.,  -4., -11.,  -3., -46., -28., -16.],
       [ 34.,   2., -49., -45.,  37.,  -9.,   5., -21., -39.,  34.],
       [ 14.,  22., -46.,  22.,  -6., -19.,   9.,  33., -44.,  -9.],
       [ 35.,  -4.,  13., -28., -10.,  18.,  20.,   6.,  45.,  -2.],
       [-42.,   8.,  11., -19.,  44.,  41.,  18., -32., -22.,  31.],
       [ 37.,  43.,   9.,  34.,  11.,  15.,  44., -35.,  13.,  36.],
       [-18.,  -7.,   9.,  15., -22., -49.,  21., -49., -49.,  44.],
       [ 23., -47.,  -5., -17.,  30.,   2., -41.,   5.,  -9., -49.]])

9. Посчитайте сумму по последним двум осям.

In [119]:
# ваш код здесь
a[:,7:9].sum()

-150.0

In [120]:
a

array([[-19., -41.,  10.,  -1.,  -5.,  36., -45.,  38.,  23., -49.],
       [ 35.,  -4.,  36., -27.,   8.,   7., -17.,  26.,  35.,  42.],
       [ -4., -18.,  22., -30.,  -4., -11.,  -3., -46., -28., -16.],
       [ 34.,   2., -49., -45.,  37.,  -9.,   5., -21., -39.,  34.],
       [ 14.,  22., -46.,  22.,  -6., -19.,   9.,  33., -44.,  -9.],
       [ 35.,  -4.,  13., -28., -10.,  18.,  20.,   6.,  45.,  -2.],
       [-42.,   8.,  11., -19.,  44.,  41.,  18., -32., -22.,  31.],
       [ 37.,  43.,   9.,  34.,  11.,  15.,  44., -35.,  13.,  36.],
       [-18.,  -7.,   9.,  15., -22., -49.,  21., -49., -49.,  44.],
       [ 23., -47.,  -5., -17.,  30.,   2., -41.,   5.,  -9., -49.]])

10. Поменяйте две строки в матрице.

In [124]:
# ваш код здесь
a[4:6,] = 0
a

array([[-19., -41.,  10.,  -1.,  -5.,  36., -45.,  38.,  23., -49.],
       [ 35.,  -4.,  36., -27.,   8.,   7., -17.,  26.,  35.,  42.],
       [ -4., -18.,  22., -30.,  -4., -11.,  -3., -46., -28., -16.],
       [ 34.,   2., -49., -45.,  37.,  -9.,   5., -21., -39.,  34.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [-42.,   8.,  11., -19.,  44.,  41.,  18., -32., -22.,  31.],
       [ 37.,  43.,   9.,  34.,  11.,  15.,  44., -35.,  13.,  36.],
       [-18.,  -7.,   9.,  15., -22., -49.,  21., -49., -49.,  44.],
       [ 23., -47.,  -5., -17.,  30.,   2., -41.,   5.,  -9., -49.]])

|

|

|

|

|

|

|

|

|

|

|

## Решения

In [ ]:
import numpy as np

1. Создать вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [ ]:
A = np.zeros(10)
A[5] = 1
A

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

2. Создать вектор со значениями от 10 до 49.

In [ ]:
A = np.arange(10, 50)
A

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [ ]:
A = np.arange(9)
A = np.reshape(A, (3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Создать массив 3x3x3 со случайными значениями.

In [ ]:
A = np.random.randn(27)
A = np.reshape(A, (3,3,3)) # не бойтесь брать размерность больше - сам функционал не меняется
A

array([[[-0.41336332,  0.24282681, -0.42799157],
        [ 2.19514652, -0.08845199, -0.26187101],
        [ 0.65486936,  1.58429859,  0.61049483]],

       [[ 3.31091876,  0.31353579, -1.03678795],
        [-0.03668153,  0.94854215, -0.34772407],
        [-0.64978004, -0.04614266, -0.6312112 ]],

       [[ 1.7907814 ,  0.04389523, -1.46941623],
        [ 0.03594945, -0.62600865,  2.43020817],
        [ 0.44822002,  1.57768507,  3.36214885]]])

5. Создать матрицу 10x10 с 0 внутри и 1 на границах.

In [ ]:
A = np.ones([10,10])
A [1:-1, 1:-1] = 0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6. Создать матрицы  5x3 и 3x2 со случайными значениями и перемножить их.

In [ ]:
A = np.random.randn(15)
A = np.reshape(A, (5,3))
A

array([[-0.01722222, -1.41473573, -0.20005992],
       [ 0.42191763, -0.04913356,  0.45401592],
       [-0.18640826, -0.75528913, -1.0106215 ],
       [ 0.68122794,  0.28916362,  1.21614174],
       [ 0.32067439, -0.29316138,  1.45262855]])

In [ ]:
B = np.random.randn(6)
B = np.reshape(B, (3,2))
B

array([[ 1.08424121,  0.31301797],
       [-0.24584297, -0.66979163],
       [ 0.26456723,  0.15239299]])

В задании не сказано, как перемножать матрицы: поэлементно или согласно правилам матричного перемножения. Так как поэлементное умножение вызовет ошибку, потому что размерности матриц не согласуются, выполним матричное перемножение:

In [ ]:
np.dot(A, B)

array([[ 0.2762005 ,  0.91169955],
       [ 0.58965736,  0.23416589],
       [-0.28380633,  0.29352557],
       [ 0.98927781,  0.20488868],
       [ 0.80407797,  0.51810428]])

|

Создать массив 10x10 со значениями от 1 до 100.

In [ ]:
A = np.arange(1,101)
A = np.reshape(A, (10,10))
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

7. Заменить максимальный элемент матрицы на ноль.

In [ ]:
A[A == A.max()] = 0
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99,  0]])

8. Отнять среднее из каждой строки в матрице.

In [ ]:
A - A.mean()

array([[-48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5,
        -39.5],
       [-38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5,
        -29.5],
       [-28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5,
        -19.5],
       [-18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,
         -9.5],
       [ -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
          0.5],
       [  1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,
         10.5],
       [ 11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,  18.5,  19.5,
         20.5],
       [ 21.5,  22.5,  23.5,  24.5,  25.5,  26.5,  27.5,  28.5,  29.5,
         30.5],
       [ 31.5,  32.5,  33.5,  34.5,  35.5,  36.5,  37.5,  38.5,  39.5,
         40.5],
       [ 41.5,  42.5,  43.5,  44.5,  45.5,  46.5,  47.5,  48.5,  49.5,
        -49.5]])

9. Посчитать сумму по последним двум строкам.

In [ ]:
A[-2:].sum(axis=1)

array([855, 855])

10. Поменять две строки в матрице.

Поменяем первую и последнюю строки:

In [ ]:
A[[0,9]] = A[[9,0]]
A

array([[91, 92, 93, 94, 95, 96, 97, 98, 99,  0],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])